feat: Create hello world and set basic configs
shigoto-sagashi/job-domain-service pull request #1
Opened 2020-04-27 03:23 UTC by weslleysammyr

2020-04-28 01:20 UTC, edylle requested changes

2020-04-28 01:20 UTC, edylle commented on .editorconfig
> +spaces_around_operators = true
Tanto `continuation_indent_size` quanto `spaces_around_operators` não são citados na lista oficial de keys do EditorConfig: https://editorconfig-specification.readthedocs.io/en/latest/#id6
Favor, revisar e remover estas chaves caso não sejam necessárias.

2020-04-28 01:20 UTC, edylle commented on .mvn/wrapper/MavenWrapperDownloader.java
> +/*
A gente realmente precisa de um wrapper do Maven? Somente o arquivo `pom.xml` não seria o suficiente?

2020-04-28 01:20 UTC, edylle commented on pom.xml
> +	<packaging>war</packaging>
Este serviço será um serviço REST somente. Não iremos inicia-lo como uma aplicação WEB ou adicionar arquivos html ou código de frontend nele.
Eu acredito que o mais indicado aqui seria um empacotamento do tipo `jar`.
Existe alguma razão para você ter escolhido `war` ao invés de `jar`?

2020-05-01 04:10 UTC, patrick29 commented on .editorconfig
> +spaces_around_operators = true
Pelo que vi os campos spaces_around_operators, max_line_length e continuation_indent_size também não são. Tem problema?

2020-05-01 04:16 UTC, patrick29 commented on .mvn/wrapper/MavenWrapperDownloader.java
> +/*
Em qual cenário ele seria necessário?

2020-05-01 04:19 UTC, patrick29 commented on pom.xml
> +	<packaging>war</packaging>
Já não lembro mais, mas pra expor o serviço pra acesso externo não tem que ser empacotado em war?

2020-05-01 04:23 UTC, patrick29 reviewed
Tirando os detalhes que o Édylle levantou não vi nada mais.

2020-05-04 23:12 UTC, edylle commented on .mvn/wrapper/MavenWrapperDownloader.java
> +/*
@patrick29 Ele seria necessário caso você não queira instalar/configurar o maven local na sua máquina. Aí este arquivo funciona como se fosse um bundle do Maven já dentro do projeto.
Creio eu que todos aqui temos, ou deveríamos, ter o maven configurado em nossas máquinas. Daí o meu questionamento da necessidade deste arquivo dentro do projeto.

2020-05-04 23:14 UTC, edylle commented on pom.xml
> +	<packaging>war</packaging>
@patrick29 Não. O empacotamento `.jar` é mais padrão e utilizado. O projeto do Genie, por exemplo, era um `.jar` e nós tínhamos tanto endpoints quanto páginas html disponíveis para acesso externo.

2020-05-19 01:38 UTC, weslleysammyr commented on .editorconfig
> +spaces_around_operators = true
Não existe problema em esses atributos estarem presentes no arquivo do `.editorconfig`, uma vez que eles, apesar de não estarem na documentação oficial, são suportados por alguns plugins, em algumas IDE's. Dessa forma, a composição do arquivo com os atributos citados, continua funcionando normalmente em qualquer outra IDE.

2020-05-19 01:40 UTC, weslleysammyr commented on .mvn/wrapper/MavenWrapperDownloader.java
> +/*
Como citado pelo @edylle, esse seria um possível cenário para o uso do wrapper.

Deixei os arquivos no pull request com o intuito de levantarmos uma discussão sobre a abordagem adotada pelo próprio time do Spring, ao incluí-lo no setup de criação dos projetos.

2020-05-19 01:42 UTC, weslleysammyr commented on pom.xml
> +	<packaging>war</packaging>
Alteração será incluída no pull request, conforme alinhado com o @edylle.

2020-05-24 19:34 UTC, edylle approved these changes

2020-05-24 19:36 UTC, merged